name: Lab1 Code Analysis

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build project
        run: |
          cd Lab1
          mvn clean install

      - name: Run SpotBugs
        run: |
          cd Lab1
          mvn spotbugs:spotbugs

      - name: Check for bugs (fails if bugs found)
        run: |
          cd Lab1
          mvn spotbugs:check

      - name: OWASP Dependency Check
        if: always()
        uses: dependency-check/Dependency-Check_Action@main
        id: dependency-check
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'Lab1'
          path: 'Lab1'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 1
            --enableRetired

      - name: Upload Dependency Check reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: ${{github.workspace}}/reports

      - name: Upload SpotBugs reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-reports
          path: Lab1/target/*.xml

